### ISSUE TITLE
Caravans are broken and overpowered

### ISSUE THREAD

**Issue by 0rion79** [k4zoo/Civ5ExpansionMod#20]
Hi, just wanna report that caravans are way too powerful. I understand that you want to implement something that the engine doesn't support and that you are looking for an alternative... Yet they are way too powerful.
They get their effect doubled, are even more powerful than an equivalent great person and provide a huge boost at any game stage: they are clearly broken.
Instead than giving a specific bonus in terms of food, gold or production, just give +1 of each and let only gold to increase over time, adding some special variable that slightly increases food and production bonus. That would make them fair.

**Comment by k4zoo** [comment]
ye just a mistake on my part, already fixed
